---
# Explicit the bastion host name, this is the server through which you connect to IE the frontend serversloadbalancer
 bastion_host: c003659alb00.neen.cloud

# array with which you explocitely specify the addresses for all the sites that you need to deploy
 site_url: ['stage.acquistaincantina.it', 'stage.vignetizanattashop.it', 'stage.viniscaliaolivashop.it', 'stage.latorderashop.it', 'stage.shop-lorenzonetto.it', 'stage.pasquashop.it','stage.shop-cantineborga.it']

# dictionary that associate sites url to magento run code for each one of the sites
 virtualhosts:
  acquistaincantina:
    url: stage.acquistaincantina.it
    code: acquista_in_cantina_it
  vignetizanattashop:
    url: stage.vignetizanattashop.it
    code: vignetizanatta_it
  viniscaliaolivashop:
    url: stage.viniscaliaolivashop.it
    code: viniscaliaoliva_it
  latorderashop:
    url: stage.latorderashop.it
    code: latordera_it
  shoplorenzonetto:
    url: stage.shop-lorenzonetto.it
    code: lorenzonetto_it
  pasquashop:
    url: stage.pasquashop.it
    code: pasqua_it
  brugnanoshop:
    url: stage.brugnanoshop.it
    code: brugnanoshop_it
  cantineborga:
    url: stage.shop-cantineborga.it
    code: borga_it
  frassina:
    url: stage.shop-frassina.it
    code: frassina_it
  poderideltodero:
    url: stage.shop-poderideltodero.it
    code: poderideltodero_it