---
#
 loadbalancer: c003659alb00.neen.cloud

# url of the site
 site_url: ['stage.acquistaincantina.it', 'stage.vignetizanattashop.it', 'stage.viniscaliaolivashop.it', 'stage.latorderashop.it', 'stage.shop-lorenzonetto.it']

# 
 virtualhosts:
  acquistaincantina:
    url: stage.acquistaincantina.it
    code: acquista_in_cantina_it
  vignetizanattashop:
    url: stage.vignetizanattashop.it
    code: vignetizanatta_it
  viniscaliaolivashop:
    url: stage.viniscaliaolivashop.it
    code: viniscaliaoliva_it
  latorderashop:
    url: stage.latorderashop.it
    code: latordera_it
  shoplorenzonetto:
    url: stage.shop-lorenzonetto.it
    code: lorenzonetto_it