---

- name: create seo config folder
  file:
    path: /var/www/{{ site_path }}/custom_conf
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ frontend_user }}"
  tags: nginx

- name: create seo config for each virtualhost
  file:
    path: /var/www/{{ site_path }}/custom_conf/{{ item.value.code }}.conf
    state: touch
    owner: "{{ frontend_user }}"
    group: "{{ frontend_user }}"
  with_dict:
    - "{{ virtualhosts }}"
  tags: nginx

- name: Push site config
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ item.value.url }}.conf
  with_dict:
    - "{{ virtualhosts }}"
  tags: nginx

- name: Symlink to sites enabled
  file:
    src: /etc/nginx/sites-available/{{ item.value.url }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.value.url }}.conf
    state: link
  with_dict:
    - "{{ virtualhosts }}"
  notify: restart nginx
  tags: nginx
