---

- name: Push  SSL config for virtualhosts
  template:
    src: virtualhost.conf.j2
    dest: /etc/nginx/sites-available/reverse.{{ item.value.url }}.conf
  with_dict:
    - "{{ virtualhosts }}"
  notify: restart nginx
  tags: nginx