---

- name: install varnish
  apt:
    name: varnish
    update_cache: yes
  tags: varnish

- name: check if stage
  stat: 
    path: /etc/varnish/stage.ansible.status
  register: stagestatus

- name: apply default neen config for varnish
  template:
    src: default.vcl.j2
    dest: /etc/varnish/default.vcl
    backup: yes
  with_dict:
    - "{{ varnish_backends }}"
  tags: varnish
  notify: reload varnish
  when: stagestatus.stat.exists == false