---
- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/block_drill
  register: block_drill
  
- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/block_drill
    state: touch
    owner: root
    group: root
  when: block_drill.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/block_location
  register: block_location

- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/block_location
    state: touch
    owner: root
    group: root
  when: block_location.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/block_robots
  register: block_robots

- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/block_robots
    state: touch
    owner: root
    group: root
  when: block_robots.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/magento2-cors.conf
  register: mag2_cors

- name: Create custom config file
  file:
    path: /etc/nginx/magento2-cors.conf
    state: touch
    owner: root
    group: root
  when: mag2_cors.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/php_custom
  register: php_custom

- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/php_custom
    state: touch
    owner: root
    group: root
  when: php_custom.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/root_custom
  register: root_custom

- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/root_custom
    state: touch
    owner: root
    group: root
  when: root_custom.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/map_custom
  register: map_custom

- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/map_custom
    state: touch
    owner: root
    group: root
  when: map_custom.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/main_custom
  register: main_custom

- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/main_custom
    state: touch
    owner: root
    group: root
  when: main_custom.stat.exists == false

- name: check if custom config file exists
  stat: 
    path: /etc/nginx/conf.d/le_wellknown
  register: le_wellknown

- name: Create custom config file
  file:
    path: /etc/nginx/conf.d/le_wellknown
    state: touch
    owner: root
    group: root
  when: le_wellknown.stat.exists == false

- name: Push no ssl config for new virtualhosts
  template:
    src: virtualhost_nossl.conf.j2
    dest: /etc/nginx/sites-available/reverse.{{ item.value.url }}.conf
    force: no
  with_dict:
    - "{{ virtualhosts }}"
  tags: nginx

- name: Enable virtualhosts via symlink
  file:
    src: /etc/nginx/sites-available/reverse.{{ item.value.url }}.conf
    dest: /etc/nginx/sites-enabled/reverse.{{ item.value.url }}.conf
    state: link
  with_dict:
    - "{{ virtualhosts }}"
  notify: restart nginx
  tags: nginx